chunk_size_kb: 10000
num_chunks: 20
warmup_iters: 50

send_bulk_data: true

min_exp_delay_ns: 100000000
recovery_delay_ns: 100000
exp_duration_ms: 7000

guard_time_ns: 200000
prealloc_delay_ns: 1000
link_rate_gbps: 10
bytes_per_req: 32768

num_rotors: 4
num_states: 2
num_hosts: 8

dummy_magic: 0x73796e63
# dummy_magic: 0x73796e11
endhost_magic: 0xbeefcafe
done_magic: 0xdeadd00d

id_to_rank:
  0: [0,8,16,24]
  1: [1,9,17,25]
  2: [2,10,18,26]
  3: [3,11,19,27]
  4: [4,12,20,28]
  5: [5,13,21,29]
  6: [6,14,22,30]
  7: [7,15,23,31]
  control: 32
  dummy: 33

rank_to_id:
  32: control
  33: dummy
  0: 0
  8: 0
  16: 0
  24: 0
  1: 1
  9: 1
  17: 1
  25: 1
  2: 2
  10: 2
  18: 2
  26: 2
  3: 3
  11: 3
  19: 3
  27: 3
  4: 4
  12: 4
  20: 4
  28: 4
  5: 5
  13: 5
  21: 5
  29: 5
  6: 6
  14: 6
  22: 6
  30: 6
  7: 7
  15: 7
  23: 7
  31: 7

rank_to_rotor:
  32: -1
  33: -1
  0: 0
  8: 1
  16: 2
  24: 3
  1: 0
  9: 1
  17: 2
  25: 3
  2: 0
  10: 1
  18: 2
  26: 3
  3: 0
  11: 1
  19: 2
  27: 3
  4: 0
  12: 1
  20: 2
  28: 3
  5: 0
  13: 1
  21: 2
  29: 3
  6: 0
  14: 1
  22: 2
  30: 3
  7: 0
  15: 1
  23: 2
  31: 3

timeslots:
  0:
    affected_rotor: 0
    rotor_state: 1
    slot_delay_us: 500
    byte_allocation_us: 3000
  1:
    affected_rotor: 1
    rotor_state: 0
    slot_delay_us: 500
    byte_allocation_us: 0
  2:
    affected_rotor: 1
    rotor_state: 1
    slot_delay_us: 500
    byte_allocation_us: 3000
  3:
    affected_rotor: 2
    rotor_state: 0
    slot_delay_us: 500
    byte_allocation_us: 0
  4:
    affected_rotor: 2
    rotor_state: 1
    slot_delay_us: 500
    byte_allocation_us: 3000
  5:
    affected_rotor: 3
    rotor_state: 0
    slot_delay_us: 500
    byte_allocation_us: 0
  6:
    affected_rotor: 3
    rotor_state: 1
    slot_delay_us: 500
    byte_allocation_us: 3000
  7:
    affected_rotor: 0
    rotor_state: 0
    slot_delay_us: 500
    byte_allocation_us: 0
  8:
    affected_rotor: 0
    rotor_state: 2
    slot_delay_us: 500
    byte_allocation_us: 3000
  9:
    affected_rotor: 1
    rotor_state: 0
    slot_delay_us: 500
    byte_allocation_us: 0
  10:
    affected_rotor: 1
    rotor_state: 2
    slot_delay_us: 500
    byte_allocation_us: 3000
  11:
    affected_rotor: 2
    rotor_state: 0
    slot_delay_us: 500
    byte_allocation_us: 0
  12:
    affected_rotor: 2
    rotor_state: 2
    slot_delay_us: 500
    byte_allocation_us: 3000
  13:
    affected_rotor: 3
    rotor_state: 0
    slot_delay_us: 500
    byte_allocation_us: 0
  14:
    affected_rotor: 3
    rotor_state: 2
    slot_delay_us: 500
    byte_allocation_us: 3000
  15:
    affected_rotor: 0
    rotor_state: 0
    slot_delay_us: 500
    byte_allocation_us: 0

timeslot_order: [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15]
# timeslot_order: [8,9,10,11,12,13]
# timeslot_order: [0]

total_period_ns: 8000000

mappings:
  0:
    0: []
    1: [7,4,2,3,1,6,5,0]
    2: [5,1,6,7,4,0,2,3]
  1:
    0: []
    1: [4,2,1,5,0,3,7,6]
    2: [2,6,0,4,3,5,1,7]
  2:
    0: []
    1: [1,0,5,6,7,2,3,4]
    2: [0,3,4,1,2,7,6,5]
  3:
    0: []
    1: [6,7,3,2,5,4,0,1]
    2: [3,5,7,0,6,1,4,2]
