chunk_size_kb: 100
num_chunks: 2000
warmup_iters: 100

send_bulk_data: true

min_exp_delay_ns: 100000000
recovery_delay_ns: 100000
exp_duration_ms: 8000

guard_time_ns: 1400000
prealloc_delay_ns: 1000
link_rate_gbps: 10
bytes_per_req: 32768

num_rotors: 4
num_states: 2
num_hosts: 8

dummy_magic: 0x73796e63
# dummy_magic: 0x73796e11
endhost_magic: 0xbeefcafe
done_magic: 0xdeadd00d

id_to_rank:
  0: [ 4, 5, 6, 7]
  1: [ 8, 9,10,11]
  2: [12,13,14,15]
  3: [16,17,18,19]
  4: [20,21,22,23]
  5: [24,25,26,27]
  6: [28,29,30,31]
  7: [32,33,34,35]
  control: [0,1,2,3]
  dummy: 36

rank_to_id:
  0: control
  1: control
  2: control
  3: control
  4:  0
  5:  0
  6:  0
  7:  0
  8:  1
  9:  1
  10: 1
  11: 1
  12: 2
  13: 2
  14: 2
  15: 2
  16: 3
  17: 3
  18: 3
  19: 3
  20: 4
  21: 4
  22: 4
  23: 4
  24: 5
  25: 5
  26: 5
  27: 5
  28: 6
  29: 6
  30: 6
  31: 6
  32: 7
  33: 7
  34: 7
  35: 7

rank_to_rotor:
  0: -1
  1: -1
  2: -1
  3: -1
  4:  0
  5:  1
  6:  2
  7:  3
  8:  0
  9:  1
  10: 2
  11: 3
  12: 0
  13: 1
  14: 2
  15: 3
  16: 0
  17: 1
  18: 2
  19: 3
  20: 0
  21: 1
  22: 2
  23: 3
  24: 0
  25: 1
  26: 2
  27: 3
  28: 0
  29: 1
  30: 2
  31: 3
  32: 0
  33: 1
  34: 2
  35: 3

timeslots:
  0:
    affected_rotor: 0
    rotor_state: 1
    slot_delay_us: 500
    byte_allocation_us: 3000
  1:
    affected_rotor: 1
    rotor_state: 0
    slot_delay_us: 500
    byte_allocation_us: 0
  2:
    affected_rotor: 1
    rotor_state: 1
    slot_delay_us: 500
    byte_allocation_us: 3000
  3:
    affected_rotor: 2
    rotor_state: 0
    slot_delay_us: 500
    byte_allocation_us: 0
  4:
    affected_rotor: 2
    rotor_state: 1
    slot_delay_us: 500
    byte_allocation_us: 3000
  5:
    affected_rotor: 3
    rotor_state: 0
    slot_delay_us: 500
    byte_allocation_us: 0
  6:
    affected_rotor: 3
    rotor_state: 1
    slot_delay_us: 500
    byte_allocation_us: 3000
  7:
    affected_rotor: 0
    rotor_state: 0
    slot_delay_us: 500
    byte_allocation_us: 0
  8:
    affected_rotor: 0
    rotor_state: 2
    slot_delay_us: 500
    byte_allocation_us: 3000
  9:
    affected_rotor: 1
    rotor_state: 0
    slot_delay_us: 500
    byte_allocation_us: 0
  10:
    affected_rotor: 1
    rotor_state: 2
    slot_delay_us: 500
    byte_allocation_us: 3000
  11:
    affected_rotor: 2
    rotor_state: 0
    slot_delay_us: 500
    byte_allocation_us: 0
  12:
    affected_rotor: 2
    rotor_state: 2
    slot_delay_us: 500
    byte_allocation_us: 3000
  13:
    affected_rotor: 3
    rotor_state: 0
    slot_delay_us: 500
    byte_allocation_us: 0
  14:
    affected_rotor: 3
    rotor_state: 2
    slot_delay_us: 500
    byte_allocation_us: 3000
  15:
    affected_rotor: 0
    rotor_state: 0
    slot_delay_us: 500
    byte_allocation_us: 0

timeslot_order: [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15]
# timeslot_order: [8,9,10,11,12,13]
# timeslot_order: [0]

total_period_ns: 8000000

mappings:
  0:
    0: []
    1: [7,4,2,3,1,6,5,0]
    2: [5,1,6,7,4,0,2,3]
  1:
    0: []
    1: [4,2,1,5,0,3,7,6]
    2: [2,6,0,4,3,5,1,7]
  2:
    0: []
    1: [1,0,5,6,7,2,3,4]
    2: [0,3,4,1,2,7,6,5]
  3:
    0: []
    1: [6,7,3,2,5,4,0,1]
    2: [3,5,7,0,6,1,4,2]
